spring.application.name=jobtracker

spring.datasource.url=jdbc:mysql://localhost:3306/jobtracker
spring.datasource.username=root
spring.datasource.password=Jv9!MysQL#27Dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


